# EDIT THIS FILE! THIS IS SCAFFOLDING FOR YOU TO OWN!
# THIS FILE WAS ORIGINALLY GENERATED BY CONAN-UE4CLI VERSION 0.0.38.
from conans import ConanFile
import os

class CesiumNativeConan(ConanFile):
    settings = "os", "compiler", "build_type", "arch"
    generators = "json"

    cesiumNativeVersion = "0.12.0@user/dev"

    def _overrideUnreal(self, dependency):
        '''
        Adds a package as a dependency, filling in the Unreal Engine version string.

        Call this with a package reference that uses a placeholder for the channel, e.g.:
        self._requireUnreal("my-package/1.0.0@adamrehn/{}")
        '''
        self.requires(dependency.format(os.environ["UNREAL_ENGINE_VERSION"]), override=True)

    def _requireNative(self, dependency):
        self.requires("%s/%s" % (dependency, self.cesiumNativeVersion))

    def requirements(self):
        self._requireNative("cesium3dtilesselection")
        self._requireNative("cesiumasync")
        self._requireNative("cesiumgeometry")
        self._requireNative("cesiumgeospatial")
        self._requireNative("cesiumgltf")
        self._requireNative("cesiumgltfreader")
        self._requireNative("cesiumionclient")
        self._requireNative("cesiumjsonreader")
        self._requireNative("cesiumutility")

        # Use Unreal's version of third-party libraries where available
        self._overrideUnreal("openssl/ue4@adamrehn/{}")
