name: Report a bug
description: Let us know so we can fix it!
labels: ["needs triage", "bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping us improve Cesium for Unreal!
        
        First, check if the issue already exists in the [issues](https://github.com/CesiumGS/cesium-unreal/issues) page. If it does, please leave a **comment** on the existing issue instead.
        
        Otherwise, if you can't find a similar issue, describe what is happening using the text fields below.
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: What environment are you experiencing this issue in?
      value: |
        Cesium for Unreal version:
        Unreal Engine Version:
        Operating System:
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Reproduction steps
      description: "How do you trigger this bug? Please walk us through it step by step, starting from either a blank project or the Cesium for Unreal Samples. (We can triage bugs much faster when we have these steps.)"
      value: |
        1.
        2.
        3.
        ...
    validations:
      required: false
  - type: textarea
    id: evidence
    attributes:
      label: Supporting evidence
      description: Providing screenshots, videos, or GIFs of the issue helps us a lot, especially for visual bugs. If there were any error messages or logs in the console, please include those too.
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        If you can also contribute a fix, we'd absolutely appreciate it! Fixing a bug in Cesium for Unreal often means fixing a bug for numerous applications and end users. Check out the contributor guide to get started: [CONTRIBUTING.md](https://github.com/CesiumGS/cesium-unreal/tree/main/CONTRIBUTING.md)

        Let us know you're working on it, and we'd be happy to provide advice and feedback.
