#define TINYGLTF_LITTLE_ENDIAN
#define TINYGLTF_IMPLEMENTATION
#define STB_IMAGE_IMPLEMENTATION
#define STB_IMAGE_WRITE_IMPLEMENTATION
// #define TINYGLTF_NOEXCEPTION // optional. disable exception handling.
#define TINYGLTF_LITTLE_ENDIAN
#define TINYGLTF_ENABLE_DRACO
#include "tiny_gltf.h"
