
// Copyright 2020-2026 CesiumGS, Inc. and Contributors

#pragma once

#include "CesiumCommon.h"
#include "CesiumRuntime.h"
#include "GenerateMaterialUtility.h"

class UMaterialExpressionCustom;
class UMaterialExpressionIf;
class UMaterialExpressionMaterialFunctionCall;
class UMaterialExpressionParameter;
class UMaterialFunction;
class UMaterialFunctionMaterialLayer;

#if WITH_EDITOR
struct FCesiumFeaturesMetadataDescription;

struct MaterialFunctionLibrary {
  UMaterialFunction* SelectTexCoords = nullptr;
  UMaterialFunction* TransformTexCoords = nullptr;
  UMaterialFunction* GetFeatureIdsFromAttribute = nullptr;
  UMaterialFunction* GetFeatureIdsFromTexture = nullptr;
  UMaterialFunction* GetFeatureIdsFromInstance = nullptr;

  MaterialFunctionLibrary();
  bool isValid() const;
};

struct FeaturesMetadataClassification
    : public GenerateMaterialUtility::MaterialNodeClassification {
  TSet<UMaterialExpressionMaterialFunctionCall*> GetFeatureIdNodes;
  TSet<UMaterialExpressionCustom*> GetPropertyValueNodes;
  TSet<UMaterialExpressionCustom*> ApplyValueTransformNodes;
  TSet<UMaterialExpressionIf*> IfNodes;
  TSet<UMaterialExpressionParameter*> ParameterNodes;

  FeaturesMetadataClassification(
      const UMaterialFunctionMaterialLayer* pMaterialLayer,
      const MaterialFunctionLibrary& functionLibrary);
};

void ClearAutoGeneratedNodes(
    UMaterialFunctionMaterialLayer* pMaterialLayer,
    GenerateMaterialUtility::MaterialGenerationState& MaterialState,
    const MaterialFunctionLibrary& FunctionLibrary);

void RemapUserConnections(
    UMaterialFunctionMaterialLayer* pMaterialLayer,
    GenerateMaterialUtility::MaterialGenerationState& MaterialState,
    const MaterialFunctionLibrary& FunctionLibrary);

void GenerateMaterialNodes(
    FCesiumFeaturesMetadataDescription& Description,
    UMaterialFunctionMaterialLayer* pMaterialLayer,
    GenerateMaterialUtility::MaterialGenerationState& MaterialState,
    const MaterialFunctionLibrary& FunctionLibrary);

#endif
