name: Install Unreal Engine
inputs:
  unreal-engine-zip:
    required: true
    type: string
  unreal-program-name:
    required: true
    type: string
  aws-access-key-id:
    required: true
    type: string
  aws-secret-access-key:
    required: true
    type: string
runs:
  using: composite
  steps:
    - name: Download Unreal Engine
      env:
        AWS_REGION: us-east-1
        AWS_ACCESS_KEY_ID: ${{ inputs.aws-access-key-id }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.aws-secret-access-key }}
      shell: pwsh
      run: |
        mkdir -p "D:/Program Files/Epic Games"
        aws s3 cp "${{ inputs.unreal-engine-zip }}" "D:/Program Files/Epic Games/UE.zip" --no-progress
    - name: Unzip Unreal Engine
      shell: pwsh
      run: |
        7z x -mmt=8 "D:/Program Files/Epic Games/UE.zip" "-oD:/Program Files/Epic Games/"
        del "D:/Program Files/Epic Games/UE.zip"
    - name: Install Unreal Engine (older versions)
      if: ${{ inputs.unreal-program-name == 'UE_5.4' || inputs.unreal-program-name == 'UE_5.5' }}
      shell: pwsh
      run: |
        Start-Process "D:/Program Files/Epic Games/${{ inputs.unreal-program-name }}/Engine/Extras/Redist/en-us/UEPrereqSetup_x64.exe" -Args "-q" -Wait
    - name: Install Unreal Engine (5.6+)
      if: ${{ inputs.unreal-program-name != 'UE_5.4' && inputs.unreal-program-name != 'UE_5.5' }}
      shell: pwsh
      run: |
        Start-Process "D:/Program Files/Epic Games/${{ inputs.unreal-program-name }}/Engine/Extras/Redist/en-us/vc_redist.x64.exe" -Args "-q" -Wait
        
