name: Build Linux

on:
  workflow_call:
    inputs:
      runner-label:
        required: true
        type: string
      unreal-engine-version:
        required: true
        type: string
      unreal-engine-zip:
        required: true
        type: string
      unreal-program-name:
        required: true
        type: string
      upload-package-base-name:
        required: true
        type: string
      extra-choco-packages:
        required: false
        type: string
        default: ''
      clang-version:
        required: true
        type: string
jobs:
  build:
    runs-on: ${{ inputs.runner-label }}
    steps:
      - name: Display system info
        run: |
          sudo swapon --show
          cat /proc/meminfo
          apt list --installed
          sudo dpkg-query -Wf '${Installed-Size}\t${Package}\n' | sort -n
          sudo snap list
      - name: Prune unneeded packages
        run: |
          sudo apt update
          sudo dpkg-query -Wf '${Package}\n' > packages.txt
          source /etc/lsb-release
          export MAJOR_VERSION=$(echo $DISTRIB_RELEASE | grep -o '^[0-9]\+')
          wget https://cdimage.ubuntu.com/ubuntu-core/$MAJOR_VERSION/stable/current/ubuntu-core-$MAJOR_VERSION-amd64.manifest -O core.manifest
          cat core.manifest | awk -F' ' '{print $1}' > packages-keep.txt
          printf "apt\napt-utils\nbinutils\nbinutils-common\nbinutils-x86-64-linux-gnu\ncoreutils" >> packages-keep.txt
          sort packages.txt > packages.txt
          sort packages-keep.txt > packages-keep.txt
          comm -23 packages.txt packages-keep.txt > packages-remove.txt
          sudo apt remove -y $(cat packages.txt | tr '\n' ' ')
          df -h
          sudo rm -rf /usr/local/lib/android || true
          sudo rm -rf /usr/share/dotnet || true
          df -h
      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v2
        with:
          version: "18.1"
      - name: Install CMake
        uses: ssrobins/install-cmake@v1
        with:
          version: 4.4
      - name: Create some space to work in /mnt
        run: |
          sudo mkdir /mnt/work
          sudo chown $(whoami) /mnt/work
      - name: Check out minimal build files
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .github
      - name: Install Unreal Engine
        uses: ./.github/actions/install-unreal-linux
        with:
          unreal-engine-zip: ${{ inputs.unreal-engine-zip }}
          unreal-program-name: ${{ inputs.unreal-program-name }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Configure vcpkg caching
        uses: ./.github/actions/vcpkg-cache
        with:
          id: ${{ inputs.upload-package-base-name }}
      - name: Install Ninja and patchelf
        run: |
          sudo apt install -y ninja-build patchelf
      - name: Set environment variables
        run: |
          echo "CESIUM_UNREAL_VERSION=$GITHUB_REF_NAME" >> "$GITHUB_ENV"
          echo "BUILD_CESIUM_UNREAL_PACKAGE_NAME=${{ inputs.upload-package-base-name }}-$GITHUB_REF_NAME" >> "$GITHUB_ENV"
          echo "UNREAL_ENGINE_ROOT=/mnt/work/${{ inputs.unreal-program-name }}" >> "$GITHUB_ENV"
          echo "LINUX_MULTIARCH_ROOT=/mnt/work/${{ inputs.unreal-program-name }}/Engine/Extras/ThirdPartyNotUE/SDKs/HostLinux/Linux_x64/${{ inputs.clang-version }}/" >> "$GITHUB_ENV"
      - name: Build cesium-native
        run: |
          export UNREAL_ENGINE_COMPILER_DIR="${LINUX_MULTIARCH_ROOT}x86_64-unknown-linux-gnu"
          export UNREAL_ENGINE_LIBCXX_DIR="${UNREAL_ENGINE_ROOT}/Engine/Source/ThirdParty/Unix/LibCxx"
          export CESIUM_VCPKG_RELEASE_ONLY=TRUE
          cd extern
          cmake -B build -S . -G Ninja -DCMAKE_TOOLCHAIN_FILE="unreal-linux-toolchain.cmake" -DCMAKE_POSITION_INDEPENDENT_CODE=ON -DCMAKE_BUILD_TYPE=Release
          cmake --build build --config Release --target install -j8
          cd ..
          rm -rf extern
      - name: Make more swap space available
        run: |
          sudo swapoff -a
          sudo fallocate -l 10G /mnt/swapfile
          sudo chmod 600 /mnt/swapfile
          sudo mkswap /mnt/swapfile
          sudo swapon /mnt/swapfile
          sudo swapon --show
      - name: Customize BuildConfiguration.xml
        run: |
          mkdir -p ~/.config/Unreal\ Engine/UnrealBuildTool
          # - We limit parallel actions because our builds use a lot more memory than UBT thinks they will.
          # - We set the source code control Provider to None so UBT includes all files in the unity build.
          printf '<?xml version="1.0" encoding="utf-8" ?>\n<Configuration xmlns="https://www.unrealengine.com/BuildConfiguration">\n    <BuildConfiguration>\n      <MaxParallelActions>2</MaxParallelActions>\n    </BuildConfiguration>\n    <SourceFileWorkingSet><Provider>None</Provider></SourceFileWorkingSet>\n</Configuration>\n' > ~/.config/Unreal\ Engine/UnrealBuildTool/BuildConfiguration.xml
      - name: Build plugin
        run: |
          sed -i 's/\"EngineVersion\": \"5.5.0\"/\"EngineVersion\": \"${{ inputs.unreal-engine-version }}\"/g' CesiumForUnreal.uplugin
          cd $UNREAL_ENGINE_ROOT/Engine/Build/BatchFiles
          ./RunUAT.sh BuildPlugin -Plugin="$GITHUB_WORKSPACE/CesiumForUnreal.uplugin" -Package="$GITHUB_WORKSPACE/packages/CesiumForUnreal" -CreateSubFolder -TargetPlatforms=Linux
      - name: Fix RPATH
        run: |
          cd $GITHUB_WORKSPACE/packages/CesiumForUnreal/Binaries/Linux
          patchelf --print-rpath libUnrealEditor-CesiumRuntime.so
          export UPDATED_RPATH=`patchelf --print-rpath libUnrealEditor-CesiumRuntime.so | sed 's/${ORIGIN}[^:]*\/SunPosition\/Binaries\/Linux/${ORIGIN}\/..\/..\/..\/..\/Runtime\/SunPosition\/Binaries\/Linux/'`
          patchelf --force-rpath --set-rpath "$UPDATED_RPATH" libUnrealEditor-CesiumRuntime.so
      - name: Print disk space free
        run: |
          df -h
      - name: Publish plugin package artifact
        if: ${{ success() }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.BUILD_CESIUM_UNREAL_PACKAGE_NAME}}
          path: packages
