name: Test Windows

on:
  workflow_call:
    inputs:
      runner-label:
        required: true
        type: string
      unreal-engine-zip:
        required: true
        type: string
      unreal-program-name:
        required: true
        type: string
      test-package-base-name:
        required: true
        type: string
jobs:
  test:
    runs-on: ${{ inputs.runner-label }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .github
            TestsProject
      - name: Set environment variables
        run: |
          $env:CESIUM_UNREAL_VERSION=$env:GITHUB_REF_NAME
          $env:PLUGIN_PACKAGE_NAME="${{ inputs.test-package-base-name }}-${env:CESIUM_UNREAL_VERSION}"
          $env:TESTS_PROJECT_ROOT="$env:GITHUB_WORKSPACE/TestsProject"
          $env:TESTS_PROJECT_LOGS="$env:TESTS_PROJECT_ROOT/Saved/Logs"
          $env:AWS_REGION="us-east-1"

          # Make these available to subsequent steps
          echo "PLUGIN_PACKAGE_NAME=${env:PLUGIN_PACKAGE_NAME}" >> $env:GITHUB_ENV
          echo "TESTS_PROJECT_ROOT=${env:TESTS_PROJECT_ROOT}" >> $env:GITHUB_ENV
          echo "TESTS_PROJECT_LOGS=${env:TESTS_PROJECT_LOGS}" >> $env:GITHUB_ENV
          echo "AWS_REGION=${env:AWS_REGION}" >> $env:GITHUB_ENV

          # Confirm vars to the console
          echo ""
          echo PLUGIN_PACKAGE_NAME=$env:PLUGIN_PACKAGE_NAME
          echo TESTS_PROJECT_ROOT=$env:TESTS_PROJECT_ROOT
          echo TESTS_PROJECT_LOGS=$env:TESTS_PROJECT_LOGS
          echo UNREAL_BATCH_FILES_PATH=$env:UNREAL_BATCH_FILES_PATH
      - name: Install Unreal Engine
        uses: ./.github/actions/install-unreal-windows
        with:
          unreal-engine-zip: ${{ inputs.unreal-engine-zip }}
          unreal-program-name: ${{ inputs.unreal-program-name }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Download plugin artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.PLUGIN_PACKAGE_NAME}}
          path: download
      - name: Install plugin to Unreal Engine
        run: |
          dir download/CesiumForUnreal
          md "D:/Program Files/Epic Games/${{ inputs.unreal-program-name }}/Engine/Plugins/Marketplace"
          cp "download/CesiumForUnreal" "D:/Program Files/Epic Games/${{ inputs.unreal-program-name }}/Engine/Plugins/Marketplace" -r
      - name: Show plugin engine version
        run: |
          cd download/CesiumForUnreal
          dir
          Get-Content "CesiumForUnreal.uplugin" | select-string -pattern "EngineVersion"
      - name: Run Cesium tests
        timeout-minutes: 60
        run: |
          cd "D:/Program Files/Epic Games/${{ inputs.unreal-program-name }}/Engine/Binaries/Win64"
          ./UnrealEditor-Cmd.exe "$env:TESTS_PROJECT_ROOT/TestsProject.uproject" -execcmds="Automation RunTests Cesium.Unit.;quit" -nullrhi -unattended -nosplash -ReportExportPath="$env:TESTS_PROJECT_LOGS"
      - name: Display tests log
        if: always()
        run: |
          cd "$env:TESTS_PROJECT_LOGS"
          dir
          Get-Content TestsProject.log
      - name: Display tests report
        if: always()
        run: |
          cd "$env:TESTS_PROJECT_LOGS"
          Get-Content index.json
      - name: Evaluate tests results
        if: always()
        run: |
          cd "$env:TESTS_PROJECT_LOGS"

          $failedTests = ""
          $succeededTests = ""

          function Parse-Test($jsonObject) {
            $currTestName = ""
            foreach ($property in $jsonObject.PSObject.Properties) {
                $name = $property.Name
                $value = $property.Value

                if($name -eq "fullTestPath") {
                  $currTestName = $value
                }

                if($name -eq "state") {
                   if ($value -eq "Success") {
                     $global:succeededTests += $currTestName + "`n"
                   }
                   else {
                     $global:failedTests += $currTestName + "`n"
                   }
                }
            }
          }

          function Parse-Json($jsonObject) {
            foreach ($property in $jsonObject.PSObject.Properties) {
                $name = $property.Name
                $value = $property.Value

                # If the property value is another object, call function recursively
                if ($name -eq "tests" -and $value -is [System.Object[]]) {
                    for (($i = 0); $i -lt $value.Count; $i++) {
                      Parse-Test($value[$i])
                    }
                }
            }
          }

          $json = Get-Content -Path 'index.json' | ConvertFrom-Json # Read in json
          Parse-Json -jsonObject $json # Parse json

          echo " "
          if ($failedTests.Length -eq 0) {
            echo "All tests passed:"
            echo "-----------------"
            echo "$succeededTests"

            exit 0
          }
          else {
            echo "Passing tests:"
            echo "--------------"
            echo "$succeededTests"

            echo "FAILED tests:"
            echo "-------------"
            echo "$failedTests"

            exit -1
          }
